version: "3"

services:
  fabrik-api:
    build: .
    command: alembic upgrade head
    ports:
      - 8000:8000
  postgresql-db:
    image: postgres:15.2-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: DB